apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
  - manifest/namespace.yaml
  - manifest/service-account.yaml
  - manifest/deployment.yaml
  - manifest/service.yaml
  - manifest/route.yaml

configMapGenerator:
  - name: vault-config
    behavior: create
    literals:
      - config.hcl=|
          ui = true
          listener "tcp" {
            address     = "0.0.0.0:8200"
            tls_disable = 1
          }
          storage "file" {
            path = "/vault/data"
          }
          disable_mlock = true