apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault
# Define resources
resources:
- manifest/namespace.yaml
- manifest/service-account.yaml
- manifest/configmap.yaml
- manifest/deployment.yaml
- manifest/service.yaml
- manifest/route.yaml

# ConfigMap Generator for Vault Config
configMapGenerator:
  - name: vault-config
    behavior: replace
    files:
      - config/vault-config.hcl

