apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Define resources to be applied in one command
resources:
  - manifests/namespace.yaml
  - manifests/service-account.yaml
  - manifests/configmap.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/route.yaml  # Include this if you need external access via a Route

# ConfigMap Generator for Vault Config
configMapGenerator:
  - name: vault-config
    namespace: vault
    files:
      - config/vault-config.hcl

# Label all resources for easier management
commonLabels:
  app: vault
