apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Define resources to be applied in one command
resources:
  - manifest/namespace.yaml
  - manifest/service-account.yaml
  - manifest/configmap.yaml
  - manifest/deployment.yaml
  - manifest/service.yaml
  - manifest/route.yaml  # Optional for external access

# ConfigMap Generator for Vault Config
configMapGenerator:
  - name: vault-config
    behavior: replace        # Ensure any existing ConfigMap is replaced
    files:
      - config/vault-config.hcl

# Label all resources for easier management
commonLabels:
  app: vault