apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  template:
    spec:
      securityContext:
        fsGroup: 100
      containers:
        - name: vault
          securityContext:
            capabilities:
              add: ["IPC_LOCK", "SETFCAP"]
            runAsUser: 100
            runAsNonRoot: true
            readOnlyRootFilesystem: false
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
            - name: vault-data
              mountPath: /vault/data
      volumes:
        - name: vault-config
          configMap:
            name: vault-config
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-data # Make sure you have this PVC created