apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data-pvc
  namespace: vault  # Ensure this matches the namespace of your application
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Specify the amount of storage you want
  volumeMode: Filesystem  # Reference the StorageClass you created
